### ISSUE TITLE
Move zfs code into root

### ISSUE THREAD

**Issue by crosbymichael** [AkihiroSuda/containerd-zfs#5]
I think you can move the zfs code into the root of the repo so that users can just import the snapshotter without having to dig deeper.  What do you think?

**Comment by AkihiroSuda** [comment]
@crosbymichael 

Sorry for didn't notice this github issue! 😅 

I attempted to move the code into root, but could not get "static" installation working:
```
$ vi ~/gopath/src/github.com/containerd/containerd/cmd/containerd/builtins_zfs.go
$ go build github.com/containerd/containerd/cmd/containerd
cmd/containerd/builtins_zfs.go:5:8: import "github.com/AkihiroSuda/containerd-zfs" is a program, not an importable package
```
https://github.com/AkihiroSuda/containerd-zfs/compare/attempt-issue-5?expand=1

Let me know if there is a solution to fix this.

Also, I'd appreciate if you can review Makefile and vendor.conf  (and also the snapshotter code itself) 😃
